// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    DashboardLayout: typeof import('./src/components/DashboardLayout.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/Section.vue')['default']
    Toasts: typeof import('./src/components/Toasts.vue')['default']
  }
}

export {}
